Use ltn12 chunked streaming to allow for sending large files
catwell/lua-multipart-post pull request #5
Opened 2019-07-09 22:22 UTC by teejaded

Added streaming support and rfc2231 name encoding.

2019-07-10 07:17 UTC, catwell commented
Wow, thank you for the PR. I need time too look at it, probably this weekend, but that's two features which are definitely useful.

2019-07-14 11:16 UTC, catwell requested changes
Sorry for the delay, and thank you again for a great PR! I have added a few important comments that should be addressed before merging this.

@teejaded I can let you do the changes or I can do them myself, as you prefer.

If you want me to do it at least please tell me where you found the `name*` parameter :)

Then I will merge, add at least an extra test for `encode`, add CI (this is an old project and I have never done it but I should) and cut a new release.

2019-07-14 11:16 UTC, catwell commented on multipart-post.lua
> +    r = {}
Should be `local r`.

2019-07-14 11:16 UTC, catwell commented on multipart-post.lua
> +    tprintf(r, "content-disposition: form-data; name*=%s'%s'%s", _M.CHARSET, _M.LANGUAGE, url.escape(k))
Where did you find this `name*` field? `filename*` comes from [RFC6266](https://tools.ietf.org/html/rfc6266) but I have not found an equivalent for `name` anywhere.

2019-07-14 11:16 UTC, catwell commented on multipart-post.lua
> +        tprintf(r, "; filename*=%s'%s'%s", _M.CHARSET, _M.LANGUAGE, url.escape(extra.filename))
I think it would be better to keep `filename` and add `filename*` as an extra parameter to support more server-side implementations (see [RFC6266 4.3](https://tools.ietf.org/html/rfc6266#section-4.3)).

2019-07-14 11:16 UTC, catwell commented on multipart-post.lua
> -local encode = function(t, boundary)
This breaks the use of just `encode` and not `gen_request` (see README) which is how a lot of people use this module. My bad for not adding a test for that...

I agree that the ability to send large files is important but we should retain that possibility and not break backwards compatibility (this module is 7 years old and used in many places).

I propose something like [this](https://gist.github.com/catwell/d9845d3bd5ab4f5375c6a36845c0b0f5). Thoughts?

2019-07-14 11:16 UTC, catwell commented on multipart-post.lua
> +        encode(r, k, v, boundary)
This PR means you encode everything twice now. There should be a way to store those lengths in a context so it isn't necessary to recompute them.

2019-07-14 11:16 UTC, catwell commented on multipart-post.lua
> +        sources[n] = encode_source(k, t[k], boundary)
detail: `t[k]` is `v`

Also the naming of `encode` and `encode_source` is not precise enough, it should be something like `encode_header_as_string` and `encode_header_as_source` or something like that.

2019-07-14 16:54 UTC, teejaded commented
Cool, thanks for the detailed comments!  I'll look these over soon (tomorrow hopefully) and make the requested changes.

2019-09-11 00:56 UTC, teejaded commented on multipart-post.lua
> +    tprintf(r, "content-disposition: form-data; name*=%s'%s'%s", _M.CHARSET, _M.LANGUAGE, url.escape(k))
I think I interpreted this as a generic method for encoding parameters.

https://tools.ietf.org/html/rfc5987#section-3.2

Certainly, form name encoding is not essential and we could leave this out.  I think the likelyhood of someone using non-ASCII values is unlikely.

2019-09-20 12:55 UTC, catwell commented on multipart-post.lua
> +    tprintf(r, "content-disposition: form-data; name*=%s'%s'%s", _M.CHARSET, _M.LANGUAGE, url.escape(k))
Like the README (and RFC 2388) says, this syntax (from RFC 2231) is valid for file names but not for part names, which should use RFC 2047 encoding.

I also agree it matters less for `name` than for `filename`. I will go back to the original code here.

2019-09-20 14:12 UTC, catwell commented on multipart-post.lua
> +        encode(r, k, v, boundary)
Will fix after merging.

2019-09-20 14:12 UTC, merged

2019-09-20 14:24 UTC, catwell commented
Thanks again for the PR. I have merged, fixed the remaining few issues and released v1.2!